version: '3.8'

services:
  construccion-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: construccion-web
    ports:
      - "80:80"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
